server:
  port: 8080
  servlet:
    context-path: /user-flow-api

spring:
  application:
    name: user-flow-api
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2

logging:
  level:
    com:
      neoris:
        userFlowAPI: INFO
